title: Daily Dogs

email: gabby.quirk@finance.nsw.gov.au
description: >- # this means to ignore newlines until "baseurl:"
  Get a free dog every day.
baseurl: "/daily-dogs" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: gabbyeq
github_username:  gabbyq

browserTitle: Daily Dogs

stage: prototype

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

remote_theme: tjharrop/NSW-jekyll-theme
